from strategies.smarty_strat import SmartyStrat
from strategies.smarty_strat_v2 import SmartyStratV2
from strategies.smarty_strat_v3 import SmartyStratV3
from strategies.cleanliness_strat import CleanlinessStrat
